### ISSUE TITLE
sad to find that can not clone

### ISSUE THREAD

**Issue by Wang-Yanzhao** [vsbuffalo/dotfiles_archived#2]
Cloning into 'dotfiles'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by vsbuffalo** [comment]
It should be possible to clone — try using https not git. I would also recommend you fork so you can maintain your own modifications. https://github.com/vsbuffalo/dotfiles2 is the most recent version.
